GET http://localhost:8000/business/admin/daily-train-ticket/query-list?page=1&size=5&trainCode=D2&start=长沙&end=苏州
Content-Type: application/json

###



GET http://localhost:8000/business/confirm-order/query-line-count/1897568339073568768
Content-Type: application/json
token: {{token}}