GET http://localhost:8000/member/member/count
Accept: application/json
token: 123
###
POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile = 111999

###
POST http://localhost:8000/member/member/send-code
Content-Type: application/x-www-form-urlencoded

mobile = 15898459477

###
POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "15898459477",
  "code": "8888"
}


> {%
    client.log(JSON.stringify(response.body));
    client.log(JSON.stringify(response.body.data.user.token));
    client.global.set("token", response.body.data.user.token);
%}